# GitHub Pages Configuration
title: "Análisis Calidad Estimación 1PL Bayesiana"
description: "Simulación y comparación de métodos de estimación para modelos 1PL: MLE vs Bayesiano"

# Include files
include:
  - "pipeline_visualization"

# Exclude files from processing
exclude:
  - "*.py"
  - "*.pyc"
  - "__pycache__/"

# GitHub Pages settings
plugins:
  - jekyll-relative-links

# Markdown settings
markdown: kramdown
